language: cpp
dist: focal
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    packages:
    - cmake
    - lcov
    - gcovr

before_script:
- mkdir -p build && cd build
- cmake .. -DCMAKE_BUILD_TYPE='Debug' -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -DBUILD_TESTS=On -DWITH_COVERAGE=On
- cmake --build .
- cd ..

script:
  - cd build && make test && make coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
