/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockevents.h"

static const char* CMockString_data = "data";
static const char* CMockString_data_len = "data_len";
static const char* CMockString_event_1 = "event_1";
static const char* CMockString_event_2 = "event_2";

typedef struct _CMOCK_event_1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_data;
  size_t Expected_data_len;
  int Expected_data_Depth;

} CMOCK_event_1_CALL_INSTANCE;

typedef struct _CMOCK_event_2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_data;
  size_t Expected_data_len;
  int Expected_data_Depth;

} CMOCK_event_2_CALL_INSTANCE;

static struct MockeventsInstance
{
  CMOCK_MEM_INDEX_TYPE event_1_CallInstance;
  CMOCK_MEM_INDEX_TYPE event_2_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockevents_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.event_1_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_event_1);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.event_2_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_event_2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockevents_Init(void)
{
  Mockevents_Destroy();
}

void Mockevents_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void event_1(void* data, size_t data_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_event_1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_event_1);
  cmock_call_instance = (CMOCK_event_1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.event_1_CallInstance);
  Mock.event_1_CallInstance = CMock_Guts_MemNext(Mock.event_1_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_event_1,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_event_1,CMockString_data_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data_len), (void*)(&data_len), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_event_1(CMOCK_event_1_CALL_INSTANCE* cmock_call_instance, void* data, int data_Depth, size_t data_len);
void CMockExpectParameters_event_1(CMOCK_event_1_CALL_INSTANCE* cmock_call_instance, void* data, int data_Depth, size_t data_len)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  memcpy((void*)(&cmock_call_instance->Expected_data_len), (void*)(&data_len),
         sizeof(size_t[sizeof(data_len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void event_1_CMockExpect(UNITY_LINE_TYPE cmock_line, void* data, size_t data_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_event_1_CALL_INSTANCE));
  CMOCK_event_1_CALL_INSTANCE* cmock_call_instance = (CMOCK_event_1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.event_1_CallInstance = CMock_Guts_MemChain(Mock.event_1_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_event_1(cmock_call_instance, data, data_len, data_len);
}

void event_1_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* data, int data_Depth, size_t data_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_event_1_CALL_INSTANCE));
  CMOCK_event_1_CALL_INSTANCE* cmock_call_instance = (CMOCK_event_1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.event_1_CallInstance = CMock_Guts_MemChain(Mock.event_1_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_event_1(cmock_call_instance, data, data_Depth, data_len);
}

void event_2(void* data, size_t data_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_event_2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_event_2);
  cmock_call_instance = (CMOCK_event_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.event_2_CallInstance);
  Mock.event_2_CallInstance = CMock_Guts_MemNext(Mock.event_2_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_event_2,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_event_2,CMockString_data_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data_len), (void*)(&data_len), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_event_2(CMOCK_event_2_CALL_INSTANCE* cmock_call_instance, void* data, int data_Depth, size_t data_len);
void CMockExpectParameters_event_2(CMOCK_event_2_CALL_INSTANCE* cmock_call_instance, void* data, int data_Depth, size_t data_len)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  memcpy((void*)(&cmock_call_instance->Expected_data_len), (void*)(&data_len),
         sizeof(size_t[sizeof(data_len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void event_2_CMockExpect(UNITY_LINE_TYPE cmock_line, void* data, size_t data_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_event_2_CALL_INSTANCE));
  CMOCK_event_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_event_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.event_2_CallInstance = CMock_Guts_MemChain(Mock.event_2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_event_2(cmock_call_instance, data, data_len, data_len);
}

void event_2_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* data, int data_Depth, size_t data_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_event_2_CALL_INSTANCE));
  CMOCK_event_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_event_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.event_2_CallInstance = CMock_Guts_MemChain(Mock.event_2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_event_2(cmock_call_instance, data, data_Depth, data_len);
}

