/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKEVENTS_H
#define _MOCKEVENTS_H

#include "unity.h"
#include "events.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockevents_Init(void);
void Mockevents_Destroy(void);
void Mockevents_Verify(void);




#define event_1_Expect(data, data_len) event_1_CMockExpect(__LINE__, data, data_len)
void event_1_CMockExpect(UNITY_LINE_TYPE cmock_line, void* data, size_t data_len);
#define event_1_ExpectWithArray(data, data_Depth, data_len) event_1_CMockExpectWithArray(__LINE__, data, data_Depth, data_len)
void event_1_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* data, int data_Depth, size_t data_len);
#define event_2_Expect(data, data_len) event_2_CMockExpect(__LINE__, data, data_len)
void event_2_CMockExpect(UNITY_LINE_TYPE cmock_line, void* data, size_t data_len);
#define event_2_ExpectWithArray(data, data_Depth, data_len) event_2_CMockExpectWithArray(__LINE__, data, data_Depth, data_len)
void event_2_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* data, int data_Depth, size_t data_len);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
